### ISSUE TITLE
医药查询平台下的方剂信息数据处理bug。

### ISSUE THREAD

**Issue by glacierck** [wangtao2001/ReasonableMedicationQASystem#1]
我检查了医药查询平台下的方剂信息数据发现了些大概是因为判空代码错误引起的错误数据，下N行数据错误的复制了当前行“分类”，“趣味记忆”等字段的值（全部属性都有这现象）。请问能提供下原始数据吗？我打算重新生成shortDict完整属性.txt文件。错误数据如下图：
![image](https://user-images.githubusercontent.com/21599896/216559904-a75014a9-0266-400f-b047-733e4effd08f.png)

**Comment by wangtao2001** [comment]
仓库中包含爬虫代码，您可以尝试重新运行，我暂时无法提供原始数据。

**Comment by wangtao2001** [comment]
closed
